/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCustomVariables: typeof import('./components/AddCustomVariables.vue')['default']
    DefineVariable: typeof import('./components/DefineVariable.vue')['default']
    ModelLoader: typeof import('./components/ModelLoader.vue')['default']
    ModelWatcher: typeof import('./components/ModelWatcher.vue')['default']
    PropertiesPanel: typeof import('./components/PropertiesPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMesh: typeof import('./components/SelectMesh.vue')['default']
    SelectMeshSide: typeof import('./components/SelectMeshSide.vue')['default']
    SelectModel: typeof import('./components/SelectModel.vue')['default']
    SystemInference: typeof import('./components/SystemInference.vue')['default']
    ToleranceThreshold: typeof import('./components/ToleranceThreshold.vue')['default']
  }
}
